Lost_and_found_management_system/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""
URL configuration for Lost_and_found_management_system project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('super-admin/', admin.site.urls),
    path('', include('home_page.urls')),
    path('admin/', include('admin_auth.urls')),
    path('administrator/', include('administrator.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_auth/urls.py
from django.urls import path
from . import views

app_name = 'admin_auth'

urlpatterns = [
    path('', views.login_page),
    path('login/', views.login, name='login'),
]

administrator/urls.py
from django.urls import path
from . import views

app_name = 'administrator'

urlpatterns = [
    path('', views.admin_home, name='admin_home'),
    path('matched/', views.manage_matched_items, name='manage_matched_items'),
    path('api/lost-items-by-category', views.lost_items_by_category, name='lost_items_by_category'),
]

home_page/urls.py
from django.urls import path
from . import views

app_name = 'home_page'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('submit-lost-item/', views.item_lost_report),
    path('recognize-image/', views.recognize_image),
    path('submit-found-item/', views.item_found_report)
]

administrator/models.py
from django.db import models

# Create your models here.

administrator/views.py
from django.shortcuts import render
from admin_auth.models import Admin
from django.http import JsonResponse
from home_page.models import LostItem
from django.db.models import Count

# Create your views here.
def admin_home(request):
    user_admin = Admin.objects.filter(username=request.GET.get('username')).first()
    request.session['user_id'] = user_admin.id
    request.session['name'] = f"{user_admin.first_name} {user_admin.last_name}"
    request.session['username'] = user_admin.username
    request.session['email'] = user_admin.email
    request.session['contact_number'] = user_admin.contact_number  
    request.session['last_login'] = user_admin.last_login.strftime('%Y-%m-%d %H:%M:%S') if user_admin.last_login else None
    request.session['date_joined'] = user_admin.date_joined.strftime('%Y-%m-%d %H:%M:%S')
    return render(request, 'administrator/admin.html')

def manage_matched_items(request):
    return render(request, 'administrator/manage_item.html')

def lost_items_by_category(request):
    data = (
        LostItem.objects.values('category')
        .annotate(count=Count('category'))
        .order_by('category')
    )
    return JsonResponse(list(data), safe=False)

administrator/templates/administrator/admin.html
{% extends 'admin_base.html' %}
{% load static %}

{% block title %}Admin Panel{% endblock %}

{% block extra_css%}
<link rel="stylesheet" href="{% static 'css/admin_base.css' %}">
{% endblock %}

{% block navbar %}
<nav class="sidebar">
    <div class="logos">
        <img src="{% static 'img/snsu-logo.png' %}" alt="">
        <img src="{% static 'img/usc-logo2.png' %}" alt="">
    </div>
    <a href="{% url 'administrator:admin_home' %}">Dashboard</a>
    <a href="#">Manage Admins</a>
    <a href="{% url 'administrator:manage_matched_items' %}">Manage Items</a>
    <a href="#">Reports</a>
    <a href="#">Settings</a>
    <a href="{% url 'admin_auth:login' %}">Logout</a>
</nav>

<div class="navbar">
    <h2>Welcome, {{ request.session.name }}</h2>
    <img src="" alt="admin picture">
</div>
{% endblock %}

{% block content %}
<div class="content">
    <div class="dashboard">
        <h1>Admin Dashboard</h1>
        <div class="cards">
            <div class="card">
                <p id="total-matched-report">Processing...</p>
                <p>Total Matched</p>
            </div>
            <div class="card">
                <p id="total-found-report">Processing...</p>
                <p>Total Found</p>
            </div>
            <div class="card">
                <p id="total-lost-report">Processing...</p>
                <p>Total Lost</p>
            </div>
        </div>
    </div>

    <div class="visualizations">
        <h2>Data Overview</h2>
        <div class="progress-bars">
            <div class="progress-bar">
                <p>Total Matched</p>
                <div class="bar">
                    <div id="matched-progress" class="fill" style="width: 0%;">0%</div>
                </div>
            </div>
            <div class="progress-bar">
                <p>Total Found</p>
                <div class="bar">
                    <div id="found-progress" class="fill" style="width: 0%;">0%</div>
                </div>
            </div>
            <div class="progress-bar">
                <p>Total Lost</p>
                <div class="bar">
                    <div id="lost-progress" class="fill" style="width: 0%;">0%</div>
                </div>
            </div>
        </div>

        <div class="charts">
            <!-- add a barchart of which category is being lost -->
            <div class="chart-container barchart">
                <h3>Lost Items by Category</h3>
                <canvas id="lostCategoryChart"></canvas>
            </div>

            <div class="chart-container">
                <canvas id="dataChart"></canvas>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'js/get_reports.js' %}"></script>
<script src="{% static 'js/chart.js' %}"></script>
{% endblock %}

administrator/templates/administrator/manage_item.html
{% extends 'admin_base.html' %}
{% load static %}

{% block title %}Admin Panel{% endblock %}

{% block extra_css%}
<link rel="stylesheet" href="{% static 'css/admin_base.css' %}">
{% endblock %}

{% block navbar %}
<nav class="sidebar">
    <div class="logos">
        <img src="{% static 'img/snsu-logo.png' %}" alt="">
        <img src="{% static 'img/usc-logo2.png' %}" alt="">
    </div>
    <a href="{% url 'administrator:admin_home' %}">Dashboard</a>
    <a href="#">Manage Admins</a>
    <a href="{% url 'administrator:manage_matched_items' %}">Manage Items</a>
    <a href="#">Reports</a>
    <a href="#">Settings</a>
    <a href="{% url 'admin_auth:login' %}">Logout</a>
</nav>

<div class="navbar">
    <h2>Welcome, {{ request.session.name }}</h2>
    <img src="" alt="admin picture">
</div>
{% endblock %}

{% block content %}
{% endblock %}